### PR TITLE
Install netCDFCxxConfig.cmake

### LINKED ISSUE #43: CMake Config files missing on install.
It seems that the current code is missing the correct CMake files allowing the netCDFCxx package to be found in other projects.  This is the error returned by ccmake:

>CMake Error at CMakeLists.txt:100 (find_package):
>   By not providing "FindnetCDFCxx.cmake" in CMAKE_MODULE_PATH this project
>   has asked CMake to find a package configuration file provided by
>   "netCDFCxx", but CMake did not find one.
>
>   Could not find a package configuration file provided by "netCDFCxx" with
>   any of the following names:
>
>     netCDFCxxConfig.cmake
>     netcdfcxx-config.cmake
>
>   Add the installation prefix of "netCDFCxx" to CMAKE_PREFIX_PATH or set
>   "netCDFCxx_DIR" to a directory containing one of the above files.  If
>   "netCDFCxx" provides a separate development package or SDK, be sure it has
>   been installed.

After being called in CMakeLists with:
`find_package(netCDFCxx REQUIRED)`
`include_directories(${NETCDFCxx_INCLUDE_PATH})`

The netCDFCxx installer only installs the CMake file `netCDFCxxConfigVersion.cmake` in:
`./lib64/cmake/netCDFCxx`

### PR DESCRIPTION
**Pull request by ZedThree**
Fixes #43 

An issue here that I've not fixed as it needs a decision from the maintainers: the installed target is `netcdf-cxx4` (with a `netCDF::` namespace). I think it might be more idiomatic if it were called `netCDF_CXX`, or `NetCDF_CXX`. The C API installs `netCDF`.

### CODE REVIEW

**Comment by j-eser** [comment]
Is there any update? I installed the library via conda and still there is no netCDFCxxConfig.cmake.
Is there an alternative solution for using this library in external cmake file?
Thanks

**Comment by r3n4ud** [comment]
Any plan on merging this?

**Comment by WardF** [comment]
Yes; we are wrapping up a Fortran release and then I will get this rolled out into a release.

**Comment by r3n4ud** [comment]
Great news, thank you!

Your merging has failed since there are two "traverse directory section"... I've fixed this on my fork yesterday on my own branch (using @ZedThree 's commit and resolving the merge with master manually). See https://github.com/r3n4ud/netcdf-cxx4/tree/cmake-dev, maybe you could use that? Warning: I pushed
- a fix on a failing H5free_memory checking, 
- an updated find hdf5,
- an added find Threads (my hdf5 targets need Threads::Threads...)

Let me know if you would a pull request from my fork/cmake-dev branch

**Comment by ZedThree** [comment]
I've fixed the merge, plus some other issues I came across. It now works consistently with netCDF-C CMake and autoconf builds.

@WardF I think you need to make a decision on naming. This currently installed a package called `netCDFCxx`, but the target is `netCDF::netcdf-cxx4` which feels a bit inconsistent. The C version exports a package `netCDF` and the target is just `netcdf`.

**Comment by ZedThree** [comment]
Travis is failing with errors like `cxx4/CMakeFiles/netcdf-cxx4.dir/build.make:487: *** target pattern contains no '%'.  Stop.`

I can't reproduce this locally, even in the docker container!

**Comment by ZedThree** [comment]
Turns out I was using an older version of the C library. It now exports the target `netCDF::netcdf`, so this exporting `netCDF::netcdf-cxx4` feels more consistent. I'm still not sure about the package name though.

**Comment by WardF** [comment]
It looks good to me! Thanks @ZedThree

**Pull request merged**
