### PR TITLE
Aodhan

### PR DESCRIPTION
**Pull request by AodhanSweeney**
New pull request so that Ward can see current edits

### CODE REVIEW

**Comment by WardF** [comment]
Thanks Aodhan, reviewing now :).

**Comment by AodhanSweeney** [comment]
There is lots of stuff commented out that for current purposes you can just ignore, new wrappers have been added in ncVar and in ncFile and I made a ncFill as well to house the set_fill function

**Comment by AodhanSweeney** [comment]
Sounds good ward! I'll look at it later on today. Thanks for the help!

**Comment by WardF** [comment]
Thanks again @AodhanSweeney! Getting this merged in.

**Pull request merged**
