### PR TITLE
Add open and close methods for NcFile

### LINKED ISSUE #17: Errors with rvalue references in C++11 mode
The following code throw a `NcBadId` exception at the `auto attr = wrap.file.getAtt("Conventions");` line.

```cpp
#include <string>
#include <netcdf>

using namespace std;
using namespace netCDF;

class Wrapper {
public:
    Wrapper(string name, string mode) {
        if (mode == "r")
            file = NcFile(name, NcFile::read);
        else if (mode == "w")
            file = NcFile(name, NcFile::write);
    }
    NcFile file;
};

int main(int argc, char** argv) {
    Wrapper wrap("file.nc", "r");
    auto attr = wrap.file.getAtt("Conventions");
    return 0;
}
```

While when I use direct initialisation for the `file` member, everything works.

```cpp
class Wrapper {
public:
     Wrapper(string name, string mode) : file(name, NcFile::read) {}
    NcFile file;
};
```

Maybe the library is using the default generated `operator=(const NcFile&)`, and this one is not correct. My compiler is clang based on LLVM 3.5.

### PR DESCRIPTION
**Pull request by Luthaf**
Fix #17

### CODE REVIEW

**Comment by WardF** [comment]
Thanks for the issue report and patch; I will review soon and merge if there aren't any problems. Thanks!

**Comment by Luthaf** [comment]
Any news on this ?

**Comment by WardF** [comment]
Thanks for the ping; I've made the merge and am currently adding some tests to our CI system.  I will push the update back to github later today.  Thanks again, sorry for the delay!

**Comment by Luthaf** [comment]
Thank you for merging this ! 

I see that you are currently porting the build system to CMake, and I need to use netcdf-cxx as part of a Cmake based-build. So if you need some help to make to CMake build fully usable, let me know!

**Pull request merged**
