### PR TITLE
FIX: generate ncxx4-config in cmake builds

### PR DESCRIPTION
**Pull request by kmuehlbauer**
This adds generation of ncxx4-config to the cmake build. Directly adapted from the configure approach. Tested locally.

Solves #36. In urgent need for https://github.com/conda-forge/netcdf-cxx4-feedstock/pull/9.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
Seems like I haven't correctly applied some CMAKE variables. Fixed.

**Comment by kmuehlbauer** [comment]
There is more missing to the final ncxx4-config file. I also get an `[: too many arguments` error, but can't track it down.

**Comment by WardF** [comment]
Ok, I have a few other things on my plate but I'll try to nail this down today or possibly tomorrow.  Thank you very much for contributing this, however, it is very much appreciated!

**Comment by kmuehlbauer** [comment]
Thanks for taking the time. Still, there is something not working correctly with this PR. I'll also have another look tomorrow (european time), If you want me something to do, just ping me.

**Comment by kmuehlbauer** [comment]
@WardF Any news on that?

**Comment by kmuehlbauer** [comment]
@WardF Any news on that?

**Comment by WardF** [comment]
Hi, none yet, we had some fires to put out but now that 4.4.1 is out I'll see if I can knock this out in short order. Thanks for your patience!

**Comment by WardF** [comment]
I've identified and corrected the error; when the travis-ci checks finish I'll merge into master. Thanks again!

**Comment by WardF** [comment]
Merged, thanks again! Incidentally, I used the command line utility `shellcheck` to quickly figure out where the issue was in the script template, just FYI :).

**Comment by kmuehlbauer** [comment]
> Merged, thanks again! Incidentally, I used the command line utility shellcheck to quickly figure out where the issue was in the script template, just FYI :).

Thanks for the hint, I'll keep that in mind for the future.

As we are relying on releases, any plans for a 4.3.1 release? Otherwise we would need to build from the latest commit.

**Comment by WardF** [comment]
There haven't been a lot of changes since the previous release, so there aren't any immediate plans for a new release.  I can schedule one, but it will be in the near future; in the short-term (next few weeks) I have other priorities I have to attend to.

**Comment by kmuehlbauer** [comment]
That's fine. Shall #36 be closed then?

**Pull request merged**
